language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
before_install:
  - sudo redis-server --daemonize yes
  - python --version
  - pip install -U pip
  - pip install redis
  - pip install codecov
install:  
  - pip install .
script:
  - coverage run tests/tests.py
notifications:
  email: false
after_success:
  - codecov
